### PR TITLE
fix: Upgraded mathjax version 3 to 3.0.1

### PR DESCRIPTION
**Pull request by ManpraXSoftware**
### Description

Equation is working correctly with previous version as well but when we do right click on equation and change options, it refresh equation, at that time, it is not being rendered it correctly.

#### How Has This Been Tested?

Right click on equation and enable accessibility, it will render equation again, equation will be disappear and when you refresh whole page then it starts to work.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ManpraXSoftware!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hi @ManpraXSoftware, thank you for your contribution!

Please amend your commit message(s) to conform to [Conventional Commits](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type) standards, and update your branch with the latest changes from master.

Once that's done and the build is green we can line your changes up for engineering review.

**Comment by itsjeyd** [comment]
Hey @ManpraXSoftware, a friendly ping about amending your commit messages ⬆️ and updating the PR branch with latest master.

**Comment by itsjeyd** [comment]
Hi @ManpraXSoftware, just checking in to see if we should keep this PR open?

**Comment by itsjeyd** [comment]
Hi @ManpraXSoftware! Thanks again for this contribution. We're closing this PR now because it is stale. You may reopen this pull request, or open a new one, when you have time to come back to this work.

**Pull request closed without merging**
