### PR TITLE
chore(deps): update paragon and frontend-build to openedx scope

### PR DESCRIPTION
**Pull request by brian-smith-tcril**

### CODE REVIEW

**Comment by brian-smith-tcril** [comment]
it looks like this is likely a dupe of https://github.com/openedx/frontend-app-discussions/pull/657

**Review by arbrandes — APPROVED** [review]

**Comment by arbrandes** [comment]
This is now required for Tutor dev mode to work (see https://github.com/overhangio/tutor-mfe/pull/193).  Should we merge this one or #657?

**Comment by brian-smith-tcril** [comment]
> This is now required for Tutor dev mode to work (see [overhangio/tutor-mfe#193](https://github.com/overhangio/tutor-mfe/pull/193)). Should we merge this one or #657?

Looks like CI is failing on 657, I'll rebase this and see if it passes.

**Comment by awais-ansari** [comment]
@brian-smith-tcril @arbrandes This PR change has broken the stage and production pipeline for discussion MFE.
Screenshot 2024-02-29 at 1 47 28 PM

**Comment by brian-smith-tcril** [comment]
@awais-ansari it looks like you need to:
* update the version of the `frontend-component-header-edx` alias. `7.12.0` still has a peer dep of `"@edx/frontend-platform": "^4.0.0 || ^5.0.0",` https://www.npmjs.com/package/@edx/frontend-component-header-edx/v/7.12.0?activeTab=code
* update the version of the `frontend-component-footer-edx` alias. `6.4.0` still has a peer dep of `"@edx/frontend-platform": "^4.0.0 || ^5.0.0",` https://www.npmjs.com/package/@edx/frontend-component-footer-edx/v/6.4.0?activeTab=code

the `brand-edx.org` package shouldn't need to be updated

**Comment by awais-ansari** [comment]
@brian-smith-tcril Thanks for quick response. We have made some changes in internal and now build is green.

**Pull request merged**
