### PR TITLE
fix: render favicon and siteName in title

### LINKED ISSUE #667: Favicon and siteName not rendering in the title on Tutor
**Issue**

When we use this MFE on Tutor, I haven't had the opportunity to test it on devstack, the favicon and siteName in the title do not render. Similarly, the title is not translated into the current language, it always shows in English as is defined in the `index.html` file:
https://github.com/openedx/frontend-app-discussions/blob/ac17fd72943972590b3126b004c51c4bae8480f2/public/index.html#L4

**Possible Reason**

This is likely due to this MFE trying to access the favicon directly in the assets folder as it is being done here: 
https://github.com/openedx/frontend-app-discussions/blob/ac17fd72943972590b3126b004c51c4bae8480f2/src/index.jsx#L17

In the other MFEs, they use the `react-helmet` package to override the head tag, similar to how it is being done in the profile MFE [here](https://github.com/openedx/frontend-app-profile/blob/761995b6239bb54cca9c79c83e0cd36d2b398bab/src/head/Head.jsx#L8-L15).

**How to reproduce**

1. Install any version of [tutor](https://docs.tutor.edly.io/)
2. Create a superuser using the command: `tutor local do createuser --staff --superuser yourusername user@email.com`
3. Sign in to tutor with the created user
4. Import the demo course using the command: `tutor local do importdemocourse`
5. Visit the discussions page for the demo course at this [url](http://apps.local.edly.io:2000/discussions/course-v1:edX+DemoX+Demo_Course/posts)

Or you can just visit the sandbox environment, which is running Tutor version 17.0.0. You can visit it at this [link](https://apps.sandbox.openedx.edly.io/discussions/course-v1:edX+DemoX+Demo_Course/posts)

### PR DESCRIPTION
**Pull request by Danyal-Faheem**
### Description

Fixes #667.

**Changes**

- Added the `react-helmet` package to add a favicon and sitename from configuration.
- Added a new `Head` component similar to the other MFEs.
- Removed the favicon static import in favor of getting it from the configuration.
- Added a `discussions.page.title` translation for every language (might be wrong), so that the title can be translated into other languages as well.
- I have just added the `discussions.app.title` as the `discussions.page.title` in each translation for now, but I realize this could be entirely wrong. I just added this as a reference for how the change would work.

#### How Has This Been Tested?

Using the [docs](https://github.com/overhangio/tutor-mfe?tab=readme-ov-file#mfe-development) provided by Tutor, I mounted my branch with the changes and tested using the steps:

1. Create a superuser using the command: `tutor local do createuser --staff --superuser yourusername user@email.com`
2. Sign in to tutor with the created user
3. Import the demo course using the command: `tutor local do importdemocourse`
4. Visit the discussions page for the demo course at this [url](http://apps.local.edly.io:2000/discussions/course-v1:edX+DemoX+Demo_Course/posts)
5. The favicon and the sitename will render.

#### Screenshots

Adding sample screenshots of the tab view in Google Chrome for sitename: `My Open edx` (Default on Tutor) and the `tutor-indigo` favicon

Before:
image

After:
image

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
Not applicable

* [x] Is there adequate test coverage for your changes?
I have added a similar test as there was for the other MFEs.

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by awais-ansari** [comment]
@Danyal-Faheem Thanks for your contributions! Do you need any review on this PR? Please attach screenshots of the before and the after effects of this change.

**Comment by Danyal-Faheem** [comment]
> @Danyal-Faheem Thanks for your contributions! Do you need any review on this PR? Please attach screenshots of the before and the after effects of this change.

Hi @awais-ansari, I've added the sample before and after screenshots in the PR description. 

As for the review, I definitely require one for the PR, especially for the translations as I've just added them as placeholders. I can remove them if required. I didn't add a reviewer as I didn't know who to add.

Let me know if you require something else from my side.

**Comment by awais-ansari** [comment]
@Danyal-Faheem Please update this PR for review.

**Comment by Danyal-Faheem** [comment]
Hi @awais-ansari. I've updated the PR with the requested changes. Can you let me know if anything else is required?

**Comment by awais-ansari** [comment]
hello @Danyal-Faheem, Lint checks are failing on this PR. Can you please have a look?

**Comment by Danyal-Faheem** [comment]
Hi @awais-ansari , sorry for that. The lint checks should be passing now. Can you review it for me now?

**Review by awais-ansari — CHANGES_REQUESTED** [review]
We have updated the translation mechanism. We do not have a messages folder in the master branch. Please update your folk repo and rebase this branch again. 
Screenshot 2024-04-05 at 1 34 28 AM

**Comment by awais-ansari** [comment]
Other than this change all looks good to me.

**Comment by Danyal-Faheem** [comment]
Hi @awais-ansari , sorry for that. Can you take another look at this now?

**Review by awais-ansari — APPROVED** [review]

**Review by sundasnoreen12 — APPROVED** [review]

**Pull request merged**
