### PR TITLE
feat: Add support for loading themes at runtime

### PR DESCRIPTION
**Pull request by xitij2000**
### Description

This PR updates this repo to use the version of Paragon with design tokens, and runtime theming. 

#### How Has This Been Tested?

To test the changes in this PR you need to set things up as follows:

1. Run `npm install --legacy-peer-deps` to install the packages. This is installing current WIP versions so this allows installation despite conflicts. 
2. Create `module.config.js` file with the following contents: 
```javascript
module.exports = {
  localModules: [
    { moduleName: '@edx/frontend-platform', dir: '../frontend-platform', dist: 'src' },
  ],
};
```
Note that the 'dir' key above should point to where you've checked out `frontend-platform` to the correct version. i.e the version in pacakge.json
3. If using tutor, shut down the discussion MFE and add the following content to .env.private:
```bash
BASE_URL='http://apps.local.overhang.io:2002'
CREDENTIALS_BASE_URL='http://localhost:18150'
ECOMMERCE_BASE_URL='http://localhost:18130'
LMS_BASE_URL='http://local.overhang.io:8000'
LEARNING_BASE_URL='http://apps.local.overhang.io:2000'
LOGIN_URL='http://local.overhang.io:8000/login'
LOGOUT_URL='http://local.overhang.io:8000/logout'
MARKETING_SITE_BASE_URL='http://local.overhang.io:8000'
ORDER_HISTORY_URL='http://localhost:1996/orders'
REFRESH_ACCESS_TOKEN_ENDPOINT='http://local.overhang.io:8000/login_refresh'
APP_ID='discussions'
MFE_CONFIG_API_URL='http://local.overhang.io:8000/api/mfe_config/v1'
```
And add the following to webpack.dev.config.js:
```javascript
const { createConfig } = require('@edx/frontend-build');
const config = createConfig('webpack-dev');
config.devServer.allowedHosts = ['apps.local.overhang.io'];
module.exports = config;
```
This will allow loading the MFE from apps.local.overhang.io:2002. 

#### Screenshots/sandbox (optional):
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**

|Before|After|
|-------|-----|
|      |      |

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xitij2000!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by awais-ansari** [comment]
Hey @xitij2000, Just to confirm. Do you still need this PR? We are planning to clean up all open PRs.

**Comment by awais-ansari** [comment]
@xitij2000 closing this PR. Please reopen it whenever you start working on it. Thanks.

**Comment by openedx-webhooks** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/558&entry.1484655318=https://github.com/xitij2000&entry.752974735=2023-08-23+14:10&entry.1917517419=2023-10-31+10:21&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/558&entry.1484655318=https://github.com/xitij2000&entry.752974735=2023-08-23+14:10&entry.1917517419=2023-10-31+10:21&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
