### PR TITLE
fix: clear saved post or comment on submit [BD-38] [TNL-9630] 

### PR DESCRIPTION
**Pull request by xitij2000**
If a post or comment has been submitted, clear it from autosaved drafts so that it doesn't show up anymore.

**Test instructions**
- Without checking out this PR do the following:
  - Create a new post, and type some text. 
  - Cancel the post, and add a new one again, you should see the saved post text.
  - Refresh the page, you should see the saved text.
  - Submit the post, and try adding a new post, you will still see the saved post. 
  - Repeat the above with comments and replies
- After checking out this PR try the above again, and now the text should be retained until the post or comment is saved. Once it's saved the text should no longer be saved.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xitij2000! I've created [BLENDED-1135](https://openedx.atlassian.net/browse/BLENDED-1135) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by khchine5** [comment]
@xitij2000 Changing topic/question to comment/reply while the keeping the tinyMCE opens , it keeps the save test unchanged, and when I try to save my saved comment it doesn't work as expected. Please check my recording. 
https://www.loom.com/share/6224cf745ded457caf6c7913792d9a44

**Comment by xitij2000** [comment]
> @xitij2000 Changing topic/question to comment/reply while the keeping the tinyMCE opens , it keeps the save test unchanged, and when I try to save my saved comment it doesn't work as expected. Please check my recording. https://www.loom.com/share/6224cf745ded457caf6c7913792d9a44

The behaviour in that video is expected, and not a bug.

**Comment by xitij2000** [comment]
@khchine5 Could you review this PR?

**Review by khchine5 — APPROVED** [review]
:+1:

- [x] I tested this locally with comment and post and reply.
- [x] I read through the code

**Review by awais-ansari — APPROVED** [review]
LGTM

**Comment by edx-webhook** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/88&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-03-08+12:03&entry.1917517419=2022-03-17+06:20&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
