### PR TITLE
feat: Profile image on user posts (palm.master)

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
### Description

- Added profile image on user avatar posts

Screenshot 2023-10-11 at 19 01 23

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vladislavkeblysh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
@vladislavkeblysh Thank you for this contribution!

**Comment by mphilbrick211** [comment]
Hi @vladislavkeblysh! Just flagging that there is a failing check.

**Comment by itsjeyd** [comment]
@vladislavkeblysh Looks like there are some coverage issues, can you have a look?

**Comment by vladislavkeblysh** [comment]
@itsjeyd The coverage issues are not related to the new code added in this PR. It seems like this has been carrying over from previous PRs.

**Comment by itsjeyd** [comment]
@vladislavkeblysh I see -- the line that the codecov check is complaining about wasn't changed in this PR. Thanks for checking.

That probably means it's OK to merge the changes as is, but it'll be up to engineering reviewers to make the final call on that.

**Comment by awais-ansari** [comment]
@vladislavkeblysh This change was intentional. This feature is still in product discussion.

**Comment by vladislavkeblysh** [comment]
@awais-ansari Branch was updated.

**Comment by dyudyunov** [comment]
Closed as redundant (no new release for this version is planned)

**Pull request closed without merging**
