### PR TITLE
chore: created testing baseline

### PR DESCRIPTION
**Pull request by PKulkoRaccoonGang**
This pull request is temporary and is necessary to simplify the testing of another pull request related to the migration of the MFE to design tokens. It will be removed after testing is complete.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PKulkoRaccoonGang! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-722-6b242e.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-722-6b242e.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-722-6b242e-51564656-7224876143-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-722-6b242e-51564656-7224876143-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-722-6b242e-51564656-7224876143-tutor-requirements.txt)

**Comment by mphilbrick211** [comment]
Hi @PKulkoRaccoonGang! Just checking to see if you plan to pursue this pull request? If not, we can close for now and reopen if needed. Thanks!

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-722-6b242e.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-722-6b242e.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-722-6b242e-51564656-8232627414-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-722-6b242e-51564656-8232627414-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-722-6b242e-51564656-8232627414-tutor-requirements.txt)

**Comment by mphilbrick211** [comment]
Closing for now due to inactivity - can reopen if needed.

**Pull request closed without merging**
