### PR TITLE
feat: Editor bar visibility (palm.master)

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
### Description

- Fixed editor bar visibility when scrolling up

Screenshot 2023-10-16 at 12 09 51
Screenshot 2023-10-16 at 12 10 13

### CODE REVIEW

**Comment by itsjeyd** [comment]
@vladislavkeblysh Thank you for this contribution!

**Comment by vladislavkeblysh** [comment]
@e0d The coverage issues are not related to the new code added in this PR. It seems like this has been carrying over from previous PRs.

**Comment by awais-ansari** [comment]
@vladislavkeblysh breaking changes have been mentioned [here](https://github.com/openedx/frontend-app-discussions/pull/582#pullrequestreview-1708090531).

**Comment by vladislavkeblysh** [comment]
@awais-ansari I have seen it. I will fix it soon, thank you

**Comment by mphilbrick211** [comment]
This should be ready to merge after the master is all set.

@vladislavkeblysh - there's a failing check here, would you mind rebasing to see if it fixes itself?

**Comment by vladislavkeblysh** [comment]
@awais-ansari @mphilbrick211 Fixed comment from master

**Review by sundasnoreen12 — APPROVED** [review]
PR LGTM

**Review by awais-ansari — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@vladislavkeblysh 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/581&entry.1484655318=https://github.com/vladislavkeblysh&entry.752974735=2023-10-16+09:11&entry.1917517419=2024-01-03+12:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
