### PR TITLE
fix: improve UX to match mockups better [BD-38] [TNL-9841] [TNL-9844]

### PR DESCRIPTION
**Pull request by xitij2000**
- Move the learner header to the home page so it can use full width.
- Remove the menu icon from learner page till there is a menu in place
- Improve styling of header bar and sidebar

|Before|After|
|---|---|
|Before | After |

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xitij2000! I've created [BLENDED-1207](https://openedx.atlassian.net/browse/BLENDED-1207) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by asadazam93** [comment]
@xitij2000 Can you please add a screenshot of how it looks like now?

**Comment by xitij2000** [comment]
> @xitij2000 Can you please add a screenshot of how it looks like now?

Done.

**Review by asadazam93 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/131&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-04-15+11:32&entry.1917517419=2022-04-21+06:31&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
