### PR TITLE
chore(i18n): add languages

### PR DESCRIPTION
**Pull request by igobranco**
Add new languages: pt-PT, uk, ru,hi, cs, es-AR, es-ES, fa-IR

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @igobranco!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @asadazam93! Would you mind taking a look at this and merging if all looks good? Thanks!

**Comment by e0d** [comment]
@igobranco updated the branch from base via a merge commit.

**Comment by mphilbrick211** [comment]
Hi @asadazam93! Friendly ping on this :)

**Review by awais-ansari — COMMENTED** [review]
@igobranco Please rebase with master and let me know if it is ready for merge.

**Comment by igobranco** [comment]
@awais-ansari I've rebased the branch!

**Comment by mphilbrick211** [comment]
Hi @igobranco! The tests are up and running again. All looks good, but there are branch conflicts that need to be fixed. Thanks!

**Comment by igobranco** [comment]
@awais-ansari and @mphilbrick211 I've rebased and resolved the conflicts.

**Comment by asadazam93** [comment]
@igobranco Are all these translation languages supported by the edx-platform? And why have you added the translations text as well? I think that is expected it to be pulled in from transfix

**Comment by e0d** [comment]
@brian-smith-tcril can you chime in on the question above?

**Comment by brian-smith-tcril** [comment]
@asadazam93 
> Are all these translation languages supported by the edx-platform? 

Looking at `frontend-app-discussions` within transifex (https://app.transifex.com/open-edx/edx-platform/frontend-app-discussions/) it seems we have
| lang code | translated | reviewed |
| - | - | - |
| pt-PT | 99.53% | 99.53% |
| uk | 98.58% | 0% |
| ru | 33% | 0% |
| hi | 30.66% | 0% |
| cs | 100% | 100% |
| es-AR | 100% | 100% |
| es-ES | 100% | 100% |
| fa-IR |  85.38% | 77.83% |

It's worth asking in the translations working group to confirm which languages can be added https://openedx.atlassian.net/wiki/spaces/COMM/pages/3157524644/Translation+Working+Group

>  Why have you added the translations text as well? I think that is expected it to be pulled in from transfex

My assumption is that these came in via a manual `make pull_translations` run, but I would need @igobranco to confirm that. That being said, the convention is to add `[lang-code].json` files that only contain `{}` and let the automated jobs fill in those files (see this commit from `edx-transifex-bot` as an example https://github.com/openedx/frontend-app-discussions/commit/f7ad94997d8a6f1c8c5b3cf766216bb5dd713b6a)

**Review by saadyousafarbi — APPROVED** [review]

**Comment by awais-ansari** [comment]
@igobranco Please rebase this PR and also add a proper description.

**Review by awais-ansari — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@igobranco 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/505&entry.1484655318=https://github.com/igobranco&entry.752974735=2023-04-26+13:50&entry.1917517419=2023-06-12+10:04&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
