### PR TITLE
[BD-38] [TNL-9611] [BB-5606] Show check icons for endorsed posts

### PR DESCRIPTION
**Pull request by tecoholic**
### Description

Show the CheckCircle icon for posts which are marked as answers and show
the Verified badge icon for discussion posts marked as endorsed.

### Additional Information

- https://openedx.atlassian.net/browse/TNL-9611

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @tecoholic! I've created [BLENDED-1134](https://openedx.atlassian.net/browse/BLENDED-1134) to keep track of it in Jira.   More details are on the [BD-18](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1593934815/BD-18+Testing+Consistency+Improvements) project page.


When this pull request is ready, tag your edX technical lead.

**Review by xitij2000 — APPROVED** [review]
:+1: Just one small nit. We are generally preferring testing larger chunks of the app rather than individual components. 

i.e. instead of a new test for this component, you can add a test to the comments view to check if a comment being endorsed shows differently there. 

In this case, I don't see much benefit in that so this is good to go. 

- [x] I tested this: tested on devstack
- [x] I read through the code

**Comment by edx-webhook** [comment]
@tecoholic 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/85&entry.1484655318=https://github.com/tecoholic&entry.752974735=2022-03-08+05:29&entry.1917517419=2022-03-09+11:08&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by tecoholic** [comment]
@xitij2000 I actually tried adding a test case to the CommentView test file, instead of creating a new file. But found the data mocking seemed complex for such small change in data, I thought it would be better to put it separately.

**Pull request merged**
