### PR TITLE
fix: Persian language

### PR DESCRIPTION
**Pull request by CodeWithEmad**
This will fix the Persian language code issue(fa-ir is the code in all of the other MFEs)
also fixed some typos in the code.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @CodeWithEmad!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hey @asadazam93, would you be able to help @CodeWithEmad with the question that he raised [above](https://github.com/openedx/frontend-app-discussions/pull/555#issuecomment-1669339197)?

@CodeWithEmad Thanks for the changes!

**Comment by e0d** [comment]
Hi @CodeWithEmad , I notice there are some commit-lint failures.  Please note that we use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard?

**Comment by CodeWithEmad** [comment]
Sure. I totally forgot about the commit lint. have a look now :)

**Comment by CodeWithEmad** [comment]
@e0d since no one answered my question about the UPPER case codes for `es-ES` and `es-AR`, I refactor them as well to `es-es` and `es-ar` and rebased with master.

**Comment by itsjeyd** [comment]
Hey @arbrandes, has this PR made it into your review queue? If you don't think you'll get to this PR anytime soon, I can try and find someone else to review; just let me know.

**Comment by mphilbrick211** [comment]
Hi @arbrandes! Just following up on this to see if you're able to review (and if you could please re-enable the checks to run)? Thanks!

CC: @itsjeyd

**Comment by itsjeyd** [comment]
@arbrandes Since your review queue is quite long (😅), would it help if we asked someone from the [maintainer team](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3575611432/Pilot+Phase+2) (Infinity) to review this PR?

CC @mphilbrick211

**Review by saadyousafarbi — APPROVED** [review]
@CodeWithEmad can you please rebase and squash your commits? Thanks!

**Comment by CodeWithEmad** [comment]
@saadyousafarbi take a look.

**Comment by e0d** [comment]
I notice there are some commit-lint failures.  Please note that we use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard?

**Comment by CodeWithEmad** [comment]
Oops. I forgot that, again!
It's okay now, @e0d.

**Comment by mphilbrick211** [comment]
Hi @arbrandes! When you get a chance, could you please re-enable the checks to run on this PR before review? Thanks!

**Comment by itsjeyd** [comment]
@mphilbrick211 @arbrandes Since @saadyousafarbi already reviewed and approved these changes I [didn't think we'd need another round of review](https://github.com/openedx/frontend-app-discussions/pull/555#issuecomment-1734934568).

The build is green, too, so it looks like this PR is pretty much ready for merge.

**Review by awais-ansari — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@CodeWithEmad 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/555&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2023-08-08+10:14&entry.1917517419=2023-10-24+09:29&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
