### PR TITLE
[BD-38] [TNL-9479] [BB-5419] Integrate retrieval of moderation reason codes from the LMS settings

### PR DESCRIPTION
**Pull request by felipetrz**
### Description

This PR implements the retrieval of moderation settings from the API endpoint implemented by [this PR](https://github.com/openedx/edx-platform/pull/29831).

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @felipetrz! I've created [BLENDED-1083](https://openedx.atlassian.net/browse/BLENDED-1083) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by tecoholic** [comment]
@xitij2000 Kindly add some tests.

**Comment by edx-webhook** [comment]
@felipetrz Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/53&entry.1484655318=https://github.com/felipetrz&entry.752974735=2022-02-02+05:12&entry.1917517419=2022-03-03+11:37&entry.2133058324=No) so we can improve your experience in the future.

**Comment by xitij2000** [comment]
@tecoholic  I think this has been superceded with the main PR for adding the UI. I am closing this.

**Comment by tecoholic** [comment]
@xitij2000 Yes. I noticed the same when review the UI and was about to suggest the same.

**Pull request closed without merging**
