### PR TITLE
feat: upgraded to node v18, added .nvmrc and updated workflows

### PR DESCRIPTION
**Pull request by BilalQamar95**
## Ticket
[Upgrade Node Js from 16 to 18](https://github.com/openedx/frontend-app-discussions/issues/473)

## edx-internal PR

https://github.com/edx/edx-internal/pull/8340
This needs to be merged together.
## Description
- Added support for node v18, updated .nvmrc and workflows. 
- Updated `frontend-platform` & `frontend-build` versions
- Resolved subsequent `eslint` issues

**edx-internal PR**
https://github.com/edx/edx-internal/pull/8340
This needs to be merged together

### CODE REVIEW

**Comment by asadazam93** [comment]
@BilalQamar95 Since v16 to v18 is a big jump we do not intend to merge this PR as it will be a bigger risk. We have tried upgrading it before and it broke on production. This should be done in two steps. First v16 to v17 and then v17 to v18

**Review by awais-ansari — COMMENTED** [review]
@BilalQamar95 is this PR still required for the upgrade?

**Comment by BilalQamar95** [comment]
> @BilalQamar95 is this PR still required for the upgrade?

This PR upgrades node version to v18, @asadazam93 requested us to bump packages incrementally, so once [#508](https://github.com/openedx/frontend-app-discussions/pull/508) is merged this PR will be ready for review.

**Review by awais-ansari — COMMENTED** [review]
@BilalQamar95 [package version PR](https://github.com/openedx/frontend-app-discussions/pull/508) update has been deployed on production. Production is working fine.  Please feel free to continue working on this one.

**Comment by abdullahwaheed** [comment]
@awais-ansari @asadazam93 its ready for review now

**Review by awais-ansari — APPROVED** [review]
LGTM

**Review by ayesha-waris — APPROVED** [review]

**Pull request merged**
