### PR TITLE
feat: Enhancements to page (quince.master)

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
- Fixed font family on page 
- Fixed borders on action bar on mobile view
- Fixed newest first text overlap another text
- Fixed displaying user name on mobile view

Screenshot 2023-10-12 at 15 07 45
Screenshot 2023-10-12 at 15 07 18
Screenshot 2023-10-12 at 15 08 31
Screenshot 2023-10-12 at 15 08 15
Screenshot 2023-10-12 at 15 09 05
Screenshot 2023-10-12 at 15 08 51
Screenshot 2023-10-12 at 15 10 31
Screenshot 2023-10-12 at 15 10 14

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vladislavkeblysh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
@vladislavkeblysh Thank you for this contribution!

@jmakowski1123 With this set of changes I'm not sure if we need to step through the full product review process. It seems like they are just fixing some small visual inconsistencies. What do you think?

CC @mphilbrick211

**Comment by awais-ansari** [comment]
@vladislavkeblysh please resolve conflict. Some changes have been suggested [here](https://github.com/openedx/frontend-app-discussions/pull/577).

**Comment by itsjeyd** [comment]
Hi @vladislavkeblysh, a friendly reminder to follow up on @awais-ansari's latest [comment](https://github.com/openedx/frontend-app-discussions/pull/578#issuecomment-1801939202) about resolving conflicts, and to address [feedback](https://github.com/openedx/frontend-app-discussions/pull/577#pullrequestreview-1708183385) that you got from @sundasnoreen12 on the main PR for this change (#577).

**Comment by vladislavkeblysh** [comment]
@itsjeyd I will fix it soon, thank you!

**Comment by vladislavkeblysh** [comment]
@itsjeyd All comments fixed and branch updated.

**Review by awais-ansari — APPROVED** [review]

**Review by sundasnoreen12 — APPROVED** [review]
PR LGTM

**Comment by arbrandes** [comment]
Is this now just a matter of pressing the merge button?  Should I do it? :)

**Comment by cmltaWt0** [comment]
The master PR still in open state.
https://github.com/openedx/frontend-app-discussions/pull/577

**Comment by openedx-webhooks** [comment]
@vladislavkeblysh 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/578&entry.1484655318=https://github.com/vladislavkeblysh&entry.752974735=2023-10-12+12:38&entry.1917517419=2023-12-14+06:52&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
