### PR TITLE
feat: Add support for archived topics [BD-38] [TNL-9673]

### PR DESCRIPTION
**Pull request by xitij2000**
Topics that belong to deleted sections/subsections/units in a course are considered archived. This PR adds a new UI section for such topics and lists them there.

Screenshot 2022-03-29 at 07-17-21 Discussions localhost

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xitij2000! I've created [BLENDED-1170](https://openedx.atlassian.net/browse/BLENDED-1170) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


When this pull request is ready, tag your edX technical lead.

**Review by tecoholic — APPROVED** [review]
@xitij2000 :+1: 

- [x] I tested this: Switched the discussions provider in the [admin](http://localhost:18000/admin/discussions/discussionsconfiguration/) and added comments and deleted the unit. The unit showed up in the archived section as expected. See image below.
- [x] I read through the code
- [x] I checked for accessibility issues


archived

**Review by awais-ansari — APPROVED** [review]

**Comment by xitij2000** [comment]
> @xitij2000 can you please rebase and fix conflicts?

Done.

**Comment by openedx-webhooks** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/109&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-03-29+07:17&entry.1917517419=2022-06-29+13:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
