### PR TITLE
feat: Editor bar visibility (quince.master)

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
### Description

- Fixed editor bar visibility when scrolling up

Screenshot 2023-10-16 at 12 09 51
Screenshot 2023-10-16 at 12 10 13

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vladislavkeblysh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
@vladislavkeblysh Thank you for this contribution!

**Comment by awais-ansari** [comment]
@vladislavkeblysh breaking changes have been mentioned [here](https://github.com/openedx/frontend-app-discussions/pull/582#pullrequestreview-1708090531).

**Comment by vladislavkeblysh** [comment]
@awais-ansari I have seen it. I will fix it soon, thank you

**Comment by arbrandes** [comment]
Do we just need to press the merge button, now?  Are all issues fixed?

**Comment by itsjeyd** [comment]
@arbrandes 

> Do we just need to press the merge button, now? Are all issues fixed?

There seem to be [some issues left to fix](https://github.com/openedx/frontend-app-discussions/pull/582#issuecomment-1855266507) on the master PR, so @vladislavkeblysh might need to update this PR and the Palm backport (#581) with some follow-up changes to get them ready for merge.

**Comment by vladislavkeblysh** [comment]
@awais-ansari @mphilbrick211 Fixed comment from master

**Review by sundasnoreen12 — APPROVED** [review]
PR LGTM

**Review by awais-ansari — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@vladislavkeblysh 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/583&entry.1484655318=https://github.com/vladislavkeblysh&entry.752974735=2023-10-16+09:16&entry.1917517419=2024-01-03+12:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
