### PR TITLE
feat: Add support for specifying post close reasons [BD-38] [TNL-8843] [BB-5012]

### PR DESCRIPTION
**Pull request by xitij2000**
Adds support for specifying an edit reason when a moderator edits a user's post.

https://user-images.githubusercontent.com/118837/159861313-b4b2e842-9bda-4f0d-bb8d-13dbb84b0809.mp4

### CODE REVIEW

**Review by tecoholic — APPROVED** [review]
@xitij2000  :+1: LGTM

- [x] I tested this: The UI works as expected and displays the reason on top of the posts
- [x] I read through the code
- [x] I checked for accessibility issues

**Comment by asadazam93** [comment]
@xitij2000 can you please fix the lint?

**Comment by xitij2000** [comment]
> @xitij2000 can you please fix the lint?
Done.

**Comment by mehaknasir** [comment]
@xitij2000 an [issue](https://openedx.atlassian.net/browse/TNL-9742) is resolved recently in this PR 
[fix: removed edit reason code by mehaknasir · Pull Request #108 · openedx/frontend-app-discussions](https://github.com/openedx/frontend-app-discussions/pull/108) 

by removing editReasonCode from patch API. I believe you might want to take a look at to while rebasing this PR again.

**Comment by xitij2000** [comment]
> @xitij2000 an [issue](https://openedx.atlassian.net/browse/TNL-9742) is resolved recently in this PR [fix: removed edit reason code by mehaknasir · Pull Request #108 · openedx/frontend-app-discussions](https://github.com/openedx/frontend-app-discussions/pull/108)
> 
> by removing editReasonCode from patch API. I believe you might want to take a look at to while rebasing this PR again.

I think the issue in the original case was the default value of `edit_reason_code` was `null` which is passed to the API, and gets rejected as invalid. Setting the default value to `undefined` should fix it. I've applied that fix in this PR.

**Review by mehaknasir — APPROVED** [review]

**Comment by mehaknasir** [comment]
post edit is failing again while my local testing. I will post review again.

**Comment by mehaknasir** [comment]
I think the issue is with my cs comment service repo. Approving it.

**Review by mehaknasir — APPROVED** [review]

**Comment by edx-webhook** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/96&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-03-21+13:25&entry.1917517419=2022-04-01+07:56&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
