### PR TITLE
fix:  [BD-38] [BB-5558][TNL-9585] Fix page load to open the correct thread

### PR DESCRIPTION
**Pull request by khchine5**
**Description**
Fix page loading to open the correct post/thread.

**Supporting information**
- https://tasks.opencraft.com/browse/BB-5558
- https://openedx.atlassian.net/browse/TNL-9585

**Testing instructions** 
- Open the course discussion page.
- Open any post.
- Open any thread of that post.
- Refresh the page.
- You should have your post and threat open.

Check this recording
https://www.loom.com/share/83c80b183a2a438eb6ba467e7dc11e55

Requires https://github.com/openedx/edx-platform/pull/29992

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @khchine5! I've created [OSPR-6496](https://openedx.atlassian.net/browse/OSPR-6496) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Review by xitij2000 — CHANGES_REQUESTED** [review]

**Comment by khchine5** [comment]
@xitij2000 PR updated and CI should be green.

**Comment by xitij2000** [comment]
@khchine5 Please add tests and get the coverage up.

**Comment by khchine5** [comment]
@xitij2000 tests added, test coverage should be better than upstream.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @khchine5! I've created [BLENDED-1190](https://openedx.atlassian.net/browse/BLENDED-1190) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by openedx-webhooks** [comment]
@khchine5 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/78&entry.1484655318=https://github.com/khchine5&entry.752974735=2022-03-01+17:25&entry.1917517419=2022-04-05+07:44&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
