### PR TITLE
fix: post sharing URL

### PR DESCRIPTION
**Pull request by dyudyunov**
### Description

When MFE uses path-based deployment (common domain for all MFEs divided by path) - the copied link leads to 404 error.

~Using the page's full URL is the easiest way to fix the problem.~

~The difference in the behavior compared to the state before the fix:~

~Before the fix:~
~The copied link always leads to the "All Posts" tab of the MFE.~

~After the fix:~
~The copied link will lead to the page where it was copied. The post can be viewed in different places (e.g. "All Posts", "Topics" tabs of the MFE) so the link will lead to the post in the corresponding tab.~

#### UPD:
- refactored the fix to always construct a URL to the post page
- used the `BASE_URL` and `PUBLIC_PATH` env variables to get the discussions MFE root URL. It should work with both subdirectory and subdomain-based deployments. 
- WIP status until finishing the subdirectory deployment testing. Subdomain deployment tested on devstack (the `PUBLIC_PATH` is `'/'`)
- clipboard work is really hard to cover by test (coverage will decrease a bit)
- LMS recently started to use the discussions sidebar which has the same button "Copy Link", but it uses its own env variable `DISCUSSIONS_MFE_BASE_URL`, and will not be affected by this change (thanks @muhammadadeeltajamul for mentioning the case)

Screenshot 2023-02-17 at 17 29 48

#### UPD2:
- tested subdomain-based instance on Devstack - works as expected
- tested subdirectory-based instance (on the stage environment) - works great too

### Would be great:
- to have @muhammadadeeltajamul as a reviewer as he has made previous changes to the feature (#280) and could point out cases I didn't find (if any) or disadvantages of the fix. I've also thought about using the env variable for the base URL (or even the public path env var which I [saw in the grade book MFE](https://github.com/openedx/frontend-app-gradebook/pull/202/files#diff-da8567d3c962abaa9698255bfdb1c44e936ef3b3674ad5fab44c61abe3fbdc7dR4)) but it will require more effort and I'm not sure it worth it.

#### How Has This Been Tested?

Tested on master-based Devstack manually with both `localhost:2002/` and `localhost:2002/discussions` base URLs

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dyudyunov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by dyudyunov** [comment]
@mphilbrick211 
Hi 👋 
This one is ready for review )

**Comment by dyudyunov** [comment]
Note: I'm going to open a backport PR to Olive when this one is discussed and reviewed

**Comment by e0d** [comment]
There's a slight decrease in coverage flagged by codecov.

```
@codecovcodecov
/ codecov/patch
src/discussions/posts/post/Post.jsx#L80
Added line #L80 was not covered by tests
```

**Comment by dyudyunov** [comment]
> There's a slight decrease in coverage flagged by codecov.
> 
> ```
> @codecovcodecov
> / codecov/patch
> src/discussions/posts/post/Post.jsx#L80
> Added line #L80 was not covered by tests
> ```

hello @e0d 

after spending some time trying to cover the mentioned line with the test, I can tell it's not as trivial as it could look.

The Clipboard API is pretty tricky and the first step for trying to test it - is to upgrade the `"@testing-library/user-event"` from 13.5.0 to 14.0.0 where user events setup seems to support the [Clipboard API](https://testing-library.com/docs/user-event/clipboard/)

I'm suspecting that could be one of the reasons for not covering this line in the [previous PR](https://github.com/openedx/frontend-app-discussions/pull/280/files#diff-bfe32c44660f70768cf542829c787f65c0ee9d41bc2d80fbe27d954dd0369409R53)

Even with the newer version, there might be problems because the clipboard API works only with secure connections (as its documentation says) but tests are running with the HTTP protocol 

I would like to skip this test for now

**Comment by muhammadadeeltajamul** [comment]
@dyudyunov  We have a new feature coming 'In-context Discussion'. You can read about this feature [here] . (https://openedx.atlassian.net/wiki/spaces/COMM/pages/3470655498/Discussions+upgrade+Sidebar+and+new+topic+structure). How will this works for in-context discussion

**Comment by muhammadadeeltajamul** [comment]
@dyudyunov Yes this as you say. However when a unit is opened in learning MFE, discussion sidebar doesnot opens automatically, discussion sidebar is behind a button. So copying link this way will not directly open the post. User will have to open discussion sidebar by clicking a button and then user will be able to view the post.

**Comment by dyudyunov** [comment]
> @dyudyunov Yes this as you say. However when a unit is opened in learning MFE, discussion sidebar doesnot opens automatically, discussion sidebar is behind a button. So copying link this way will not directly open the post. User will have to open discussion sidebar by clicking a button and then user will be able to view the post.

I see

So I think the way it could work - is to use the MFE env variable (e.g. `DISCUSSION_MFE_BASE_URL` or similar) in both Learning and Discussion MFEs. It could be used to replace the `${window.location.origin}` part of the URL construction so the link will lead to the discussion post page and both subdomain and path-based deployments will work

Maybe you have better ideas?

**Comment by dyudyunov** [comment]
I've force pushed the refactored fix which works the same way (constructs the URL to the Post page) but uses discussion MFE's env vars instead `window.location.origin`

Marked the PR as WIP until tested with the subdirectory-based deployment

**Comment by dyudyunov** [comment]
@e0d @muhammadadeeltajamul 
I've tested the updated fix with both subdirectory and subdomain instances, and all work as expected.

The fix in the nutshell - is to use the `PUBLIC_PATH` env var for the post's page URL construction. It will be set to the MFE-specific value in the subdirectory-based deployments or will use the [default value](https://github.com/openedx/configuration/blob/master/playbooks/roles/mfe/defaults/main.yml#L50) for the subdomain-based deployments.

I'll open the backport PR to Olive ASAP.

Now it's ready for review 🙂 @mphilbrick211 FYI

**Comment by e0d** [comment]
@dyudyunov tests approved.

**Comment by e0d** [comment]
@dyudyunov looks like there are conflicts between the branch and master.

**Comment by e0d** [comment]
Tests approved

**Comment by mphilbrick211** [comment]
Hi @asadazam93! Would you mind reviewing this and merging if it's good-to-go? Thanks!

**Comment by asadazam93** [comment]
@dyudyunov the PUBLIC_PATH you are using is not defined in our production environment so we will not be able to merge this PR. Thank you for your suggestion.

**Comment by e0d** [comment]
@dyudyunov Looks like there are codecov issues.  The branch is also out of date, but can't be auto updated.  Can you rebase and push?

**Comment by asadazam93** [comment]
I have merged this in the olive branch but we cannot merge this in the master branch until we fix the production environment to handle PUBLIC_PATH

**Comment by arbrandes** [comment]
@asadazam93, fine by me as long as we don't forget about it.  For example, we'll have to remember to create a backport to Palm once the branch is cut if this doesn't get merged by then.  Which, it so happens, is next Monday. :)

Any idea when we'd be able to merge it?

**Comment by mphilbrick211** [comment]
> @asadazam93, fine by me as long as we don't forget about it. For example, we'll have to remember to create a backport to Palm once the branch is cut if this doesn't get merged by then. Which, it so happens, is next Monday. :)
> 
> Any idea when we'd be able to merge it?

Hi @asadazam93! Just checking in on this :)

**Comment by arbrandes** [comment]
@asadazam93, seconding @mphilbrick211 earlier request and reiterating my  question: can we merge this? :)

**Comment by dyudyunov** [comment]
@asadazam93 

I've rebased the fix on the master branch and opened a backport to Palm.master: https://github.com/openedx/frontend-app-discussions/pull/519

now I have issues with tests that are not connected with my changes
I was able to reproduce them by running tests locally on both the branch with the fix and the `master` branch. Issues are not reproducible on the palm (check the backport PR test runs).

**Comment by mphilbrick211** [comment]
@arbrandes - FYI ^

**Comment by asadazam93** [comment]
@dyudyunov we are aware of the tests failing on the master branch. We are currently working on fixing those. We had an important feature release so we did not want to fiddle with the production environment until the release was on production. I will create a ticket to fix the PUBLIC_PATH on the production environment and will try to get it done this week.

**Review by awais-ansari — COMMENTED** [review]
@dyudyunov Please rebase this branch with master. The PUBLIC_PATH issue has been addressed on the master.

**Comment by dyudyunov** [comment]
> @dyudyunov Please rebase this branch with master. The PUBLIC_PATH issue has been addressed on the master.

done

**Review by awais-ansari — APPROVED** [review]

**Review by muhammadadeeltajamul — APPROVED** [review]

**Review by AhtishamShahid — APPROVED** [review]

**Pull request merged**
