### PR TITLE
fix: update icons to match mockups better  [BD-38] [TNL-9208] [TNL-9209]

### PR DESCRIPTION
**Pull request by xitij2000**
Temporary icons were in use while certain icons were unavailable in Paragon. They have now been updated to use more appropirate icons.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xitij2000! I've created [BLENDED-1143](https://openedx.atlassian.net/browse/BLENDED-1143) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by xitij2000** [comment]
NOTE: The tests that are failing here are refactored in another PR that will merge first, so it's better to wait on that and then update them for tis.

**Review by tecoholic — APPROVED** [review]
@xitij2000  :+1:

- [x] I tested this: Verified the icons are updated
- [x] I read through the code
- [x] I checked for accessibility issues

**Review by awais-ansari — APPROVED** [review]
LGTM

**Comment by edx-webhook** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/94&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-03-14+11:59&entry.1917517419=2022-03-28+08:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
