### PR TITLE
refactor: updated lock file version check to use new workflow

### PR DESCRIPTION
**Pull request by Mashal-m**
### Description

Renamed `lockfileversion-check-v3` to `lockfile-check` in lockfile version file.
# Ticket

[Prototype a way to review NPM lockfiles in PRs](https://github.com/edx/edx-arch-experiments/issues/355)

#### How Has This Been Tested?

Please describe in detail how you tested your changes.

#### Screenshots/sandbox (optional):
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**

|Before|After|
|-------|-----|
|      |      |

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by awais-ansari** [comment]
Hi @Mashal-m, Just to confirm. Are you still working on this PR? We are planning the board cleanup. Should I close this PR?

**Comment by sundasnoreen12** [comment]
Hi @Mashal-m any updates on this PR?

**Comment by Mashal-m** [comment]
It is ready to review and merge. 

> Hi @Mashal-m any updates on this PR?

**Review by sundasnoreen12 — APPROVED** [review]
PR LGTM

**Review by awais-ansari — APPROVED** [review]

**Pull request merged**
