### PR TITLE
fix: block overflow when editing comment

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
### Description

This merge request contains a fix for the comment edit block width at small screen resolutions for course Discussions pages or discussion sidebar in MFE Learning.

### Related PR 
- quince branch: https://github.com/openedx/frontend-app-discussions/pull/705
- redwood branch: https://github.com/openedx/frontend-app-discussions/pull/710

#### Screenshots:

|Before|After|
|-------|-----|
|  image    |    image  |

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @openedx/2u-infinity @openedx/edx-infinity! This, along with it's [backport](https://github.com/openedx/frontend-app-discussions/pull/705) are ready for review. Thanks!

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7201963956-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7201963956-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7201963956-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7467138056-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7467138056-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7467138056-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7559263388.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7559263388-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7559263388-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7559263388-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7560640311.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7560640311-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7560640311-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7560640311-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7559263376-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7559263376-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7559263376-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7623608980-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7623608980-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7623608980-tutor-requirements.txt)

**Comment by awais-ansari** [comment]
> Hi @openedx/2u-infinity - are you still maintaining this repo? If so, would you mind taking a look? Thanks!

Yes, We are still managing this repo. I'll review it.

**Review by awais-ansari — APPROVED** [review]

**Comment by ihor-romaniuk** [comment]
@awais-ansari I believe everything is ready for merging of this pull request and of the backport pull request https://github.com/openedx/frontend-app-discussions/pull/705 as well. Could we proceed with that?

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7732099707-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7732099707-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7732099707-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7740168359-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7740168359-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7740168359-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7837356123-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7837356123-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7837356123-tutor-requirements.txt)

**Comment by mariajgrimaldi** [comment]
@awais-ansari: could you please help us merge this PR and the backport? Thanks!

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7923659297-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7923659297-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7923659297-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7931658289-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7931658289-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7931658289-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7938424379-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7938424379-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-7938424379-tutor-requirements.txt)

**Comment by ihor-romaniuk** [comment]
Hello @awais-ansari 
The Pull Requests has been rebased and ready for final review. Thanks.

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-706-530efe.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-706-530efe.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-8527914394-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-8527914394-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-706-530efe-51564656-8527914394-tutor-requirements.txt)

**Comment by mphilbrick211** [comment]
@openedx/2u-infinity - this is ready for review. Thanks!

**Review by sundasnoreen12 — APPROVED** [review]

**Pull request merged**
