### PR TITLE
fix: container indents and style imports

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
### Description
This pull request contains:
- a small fix for navigation container side indents and make them the same
- fix paragon and brand style imports (prepending module paths with a `~` tells webpack to search through node_modules)

### Related Pull Requests
PR to the open-release/palm.master branch: https://github.com/openedx/frontend-app-discussions/pull/599
PR to the open-release/quince.master branch: https://github.com/openedx/frontend-app-discussions/pull/601

#### Screenshots/sandbox (optional):
|Before|After|
|-------|-----|
|    image   |    image  |

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @openedx/edx-infinity! This is ready for review / merge. Thanks!

**Comment by awais-ansari** [comment]
@ihor-romaniuk Please update this PR.

**Comment by ihor-romaniuk** [comment]
@awais-ansari PR was updated

**Comment by sundasnoreen12** [comment]
@ihor-romaniuk please rebase with master again

**Review by sundasnoreen12 — APPROVED** [review]

**Review by awais-ansari — CHANGES_REQUESTED** [review]
Please rebase with the master.

**Comment by ihor-romaniuk** [comment]
@awais-ansari @sundasnoreen12 rebased

**Review by awais-ansari — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/600&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2023-11-06+15:59&entry.1917517419=2023-11-14+07:07&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
