### PR TITLE
feat: Profile image on user posts (quince.master)

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
### Description

- Added profile image on user avatar posts

Screenshot 2023-10-11 at 19 01 23

### CODE REVIEW

**Comment by arbrandes** [comment]
Is this ready to merge?

**Comment by cmltaWt0** [comment]
It hasn't yet been merged with the master.
https://github.com/openedx/frontend-app-discussions/pull/574

**Comment by itsjeyd** [comment]
This change will need product approval before merging it, see https://github.com/openedx/frontend-app-discussions/pull/574#issuecomment-1854931136.

**Comment by dyudyunov** [comment]
Closed as redundant (no new release for this version is planned)

**Pull request closed without merging**
