### PR TITLE
fix: my posts tab search

### PR DESCRIPTION
**Pull request by dyudyunov**
### Description

Fix the issue when the search on the "My Posts" tab doesn't work

This is a backport from the master branch: https://github.com/openedx/frontend-app-discussions/pull/419

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dyudyunov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by dyudyunov** [comment]
@mphilbrick211 hi!

This one is ready for review!)

**Review by awais-ansari — COMMENTED** [review]
@dyudyunov can you please add more detail or a video of the issue and a video after the fix? it would be great to identify the issue. Currently, My post tab search is working as excepted on stage and production.

**Comment by dyudyunov** [comment]
> @dyudyunov can you please add more detail or a video of the issue and a video after the fix? it would be great to identify the issue. Currently, My post tab search is working as excepted on stage and production.

@awais-ansari sure

Here is the record where:
1. I'm presenting all posts search first (as an expected behavior)
2. Then I'm trying to do the same on the My Posts tab (the actual result)

The behavior after the fix is the same for both the All Posts and My Posts tabs (I can record it separately if you need)

**NOTE:** This is a backport from the master branch, so if your stage/prod instance uses the master branch - the issue will not reproduce there

discuss_my_posts_search

**Comment by awais-ansari** [comment]
> > @dyudyunov can you please add more detail or a video of the issue and a video after the fix? it would be great to identify the issue. Currently, My post tab search is working as excepted on stage and production.
> 
> @awais-ansari sure
> 
> Here is the record where:
> 
> 1. I'm presenting all posts search first (as an expected behavior)
> 2. Then I'm trying to do the same on the My Posts tab (the actual result)
> 
> The behavior after the fix is the same for both the All Posts and My Posts tabs (I can record it separately if you need)
> 
> **NOTE:** This is a backport from the master branch, so if your stage/prod instance uses the master branch - the issue will not reproduce there
> 
> discuss_my_posts_search [ discuss_my_posts_search ](https://user-images.githubusercontent.com/47273130/224642823-c541eec6-842c-471d-a2a7-72aeb7324f1e.gif) [ ](https://user-images.githubusercontent.com/47273130/224642823-c541eec6-842c-471d-a2a7-72aeb7324f1e.gif)

@dyudyunov Thanks for the visual representation. Our team will verify, and reproduce the issue and test PR changes. We will get back to you ASAP. Please stay tuned and thanks for your contribution.

**Comment by ayeshoali** [comment]
@dyudyunov I'm unable to reproduce the bug as it's already been fixed in [PR-419](https://github.com/openedx/frontend-app-discussions/pull/419). Here's the [resolved code](https://github.com/openedx/frontend-app-discussions/blob/master/src/discussions/posts/PostsList.jsx#L53) from master branch. Stage is using master branch and the bug has already been resolved.
Thanks.

**Review by ayeshoali — APPROVED** [review]

**Comment by ayeshoali** [comment]
Approving it as olive branch does not have latest changes/fixes.
@dyudyunov Thanks for your contribution.

**Review by AhtishamShahid — APPROVED** [review]

**Review by awais-ansari — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@dyudyunov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/467&entry.1484655318=https://github.com/dyudyunov&entry.752974735=2023-03-09+13:36&entry.1917517419=2023-03-14+19:50&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
