### PR TITLE
feat: Editor bar visibility

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
### Description

- Fixed editor bar visibility when scrolling up

Screenshot 2023-10-16 at 12 09 51
Screenshot 2023-10-16 at 12 10 13

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vladislavkeblysh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
@vladislavkeblysh Thank you for this contribution!

@jmakowski1123 Another set of changes that [may or may not require product review](https://github.com/openedx/frontend-app-discussions/pull/577#issuecomment-1766566787).

* Palm backport: #581 
* Quince backport: #583 

CC @mphilbrick211

**Comment by ayub02** [comment]
@awais-ansari looks good to me.

**Review by sundasnoreen12 — CHANGES_REQUESTED** [review]
The modification of the z-index value from 3 to 9999 is impacting other sections of the MFE, as illustrated in the attached screenshots depicting the "before" and "after" states.

**Before**
Screenshot 2023-11-01 at 5 00 58 PM

**After**
Screenshot 2023-11-01 at 4 57 15 PM

**Comment by mphilbrick211** [comment]
HI @jmakowski1123 - does this have a master product ticket?

**Comment by jmakowski1123** [comment]
This is approved.

**Comment by awais-ansari** [comment]
@vladislavkeblysh did you get a chance to review this change? This is still breaking the UI.

**Comment by itsjeyd** [comment]
> This is approved.

Thank you @jmakowski1123.

@vladislavkeblysh Changing status to In Eng Review now, for this PR and Palm/Quince backports (#581, #583).

CC @awais-ansari

**Comment by vladislavkeblysh** [comment]
@awais-ansari I will see it soon, thank you for reminding!

**Review by sundasnoreen12 — APPROVED** [review]
PR LGTM

**Review by awais-ansari — APPROVED** [review]

**Comment by awais-ansari** [comment]
@vladislavkeblysh Please update the PR.

**Comment by vladislavkeblysh** [comment]
@awais-ansari done

**Comment by openedx-webhooks** [comment]
@vladislavkeblysh 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-discussions&entry.867055334=https://github.com/openedx/frontend-app-discussions/pull/582&entry.1484655318=https://github.com/vladislavkeblysh&entry.752974735=2023-10-16+09:14&entry.1917517419=2024-01-04+20:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
